/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
var CLASS$=Laya.class;
var STATICATTR$=Laya.static;
var View=laya.ui.View;
var Dialog=laya.ui.Dialog;
var Scene=Laya.Scene;
if(!window.ui) window.ui={};
var TestSceneUI=(function(_super){
		function TestSceneUI(){
			
			TestSceneUI.__super.call(this);
		}
		CLASS$(TestSceneUI,'ui.test.TestSceneUI',_super);
		var __proto__=TestSceneUI.prototype;
		__proto__.createChildren=function(){
			_super.prototype.createChildren.call(this);
			this.loadScene("test/TestScene");
		}
		return TestSceneUI;
	})(Scene);
export {ui as default};